Repository CONP-PCNO/conp-authentication, pull requests merged in 2019-03, with the labels that each got.

#1 [Auth] Turn it into a flask application
  .flaskenv
  .gitignore
  LICENSE
  README.md
  VERSION
  app/__init__.py
  app/forms.py
  app/routes.py
  app/static/css/custom.css
  app/static/img/conp-pcno-logo.png
  app/static/img/conp.ico
  app/static/img/institution-logo.png
  app/static/img/orcid-logo.png
  app/static/img/warning.png
  app/static/js/login.js
  app/templates/base.html
  app/templates/login.html
  auth.py
  config.py
  requirements.txt
Labels: Flask-specifc, discussion-required, enhancement, in-progress

#2 [SysAdmin] Add Procfile for Heroku deployment
  Procfile
Labels: Heroku, enhancement

#3 [Bug] Add width to fix style element
  app/static/css/custom.css
Labels: UI, bug, enhancement

#6 Add basic ORCID authentication
  README.md
  app/__init__.py
  app/models.py
  app/oauth.py
  app/routes.py
  app/templates/login.html
  config.py
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/7e46a8afd030_added_user_table.py
  migrations/versions/ead0be3dbfa6_add_users_oauth_column.py
  oauth_run.py
  requirements.txt
Labels: passed-manual-test
